//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TicaretTakipDatabaseFirst.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbMusteri
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbMusteri()
        {
            this.tbOdemeHareketi = new HashSet<tbOdemeHareketi>();
            this.tbSatisHareketi = new HashSet<tbSatisHareketi>();
        }
    
        public int Id { get; set; }
        public string TcKimlikNumara { get; set; }
        public string Isim { get; set; }
        public string SoyAd { get; set; }
        public int IkametId { get; set; }
        public string TamAdres { get; set; }
        public string TelefonNumarasi { get; set; }
        public string IkinciTelefonNumarasi { get; set; }
        public string MusteriAciklamasi { get; set; }
    
        public virtual tbIkamet tbIkamet { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbOdemeHareketi> tbOdemeHareketi { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbSatisHareketi> tbSatisHareketi { get; set; }
    }
}
