//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TicaretTakipDatabaseFirst.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbOdemeHareketi
    {
        public int Id { get; set; }
        public int MusteriId { get; set; }
        public string MusteriIsmiSoyIsmi { get; set; }
        public Nullable<float> OdenenTutar { get; set; }
        public Nullable<System.DateTime> Tarih { get; set; }
    
        public virtual tbMusteri tbMusteri { get; set; }
    }
}
