//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TicaretTakipDatabaseFirst.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbUrunGrubu
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbUrunGrubu()
        {
            this.tbUrun = new HashSet<tbUrun>();
        }
    
        public int Id { get; set; }
        public string UrunGrubuAciklamasi { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbUrun> tbUrun { get; set; }
    }
}
