//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TicaretTakipDatabaseFirst.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class TicaretTakipEntities1 : DbContext
    {
        public TicaretTakipEntities1()
            : base("name=TicaretTakipEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<tbIkamet> tbIkamet { get; set; }
        public virtual DbSet<tbMusteri> tbMusteri { get; set; }
        public virtual DbSet<tbOdemeHareketi> tbOdemeHareketi { get; set; }
        public virtual DbSet<tbUrun> tbUrun { get; set; }
        public virtual DbSet<tbUrunGrubu> tbUrunGrubu { get; set; }
        public virtual DbSet<tbSatisHareketi> tbSatisHareketi { get; set; }
    }
}
